steps:
- name: 'node'
  entrypoint: 'npm'
  args: ['install']
- name: 'node'
  entrypoint: 'npm'
  args: ['test']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/introsoft:$BUILD_ID', '.' ]

images:
  - 'eu.gcr.io/$PROJECT_ID/introsoft:$BUILD_ID'
