services:
  introsoft:
    build:
      context: .
    ports:
      - "2000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
    
  redis:
    image: redis

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
